### PR TITLE
fix spell errors and missing header file

### PR DESCRIPTION
**Pull request by Eightina**
With these changes, sample codes of OpenMP and Pthread can compile and run normally.

### CODE REVIEW

**Review by tonyyxliu — APPROVED** [review]
Thank you for your pull request. It is very helpful!

**Comment by tonyyxliu** [comment]
Thank you for what you've done in this PR!
We are very glad to offer you 0.5 extra credits, but we cannot know who you are and what is your student ID from GitHub. If you are interested, would you please send email to me (yuxuanliu1@link.cuhk.edu.cn) with your name or student ID.
If you think it is unnecessary, please ignore this message and I am sorry for bothering you.

**Comment by Eightina** [comment]
My name is 阙成恩 and my student number 223040076. I really appreciate you and all other TAs for your help in this course! Thanks a lot.

________________________________
发件人: Yuxuan LIU ***@***.***>
发送时间: 2023年11月1日 22:07
收件人: tonyyxliu/CSC4005-2023Fall ***@***.***>
抄送: Eightina ***@***.***>; Author ***@***.***>
主题: Re: [tonyyxliu/CSC4005-2023Fall] fix spell errors and missing header file (PR #1)


Thank you for what you've done in this PR!
We are very glad to offer you 0.5 extra credits, but we cannot know who you are and what is your student ID from GitHub. If you are interested, would you please send email to me ***@***.******@***.***>) with your name or student ID.
If you think it is unnecessary, please ignore this message and I am sorry for bothering you.

―

**Comment by tonyyxliu** [comment]
Thank you for your understanding! Your extra credits have been added on BB.

**Pull request merged**
