### PR TITLE
Update docker install guide to support latest CUDA driver version.

### PR DESCRIPTION
**Pull request by I-am-Future**
**Problem Statement**

In my late [pull request](https://github.com/tonyyxliu/CSC4005-2023Fall/pull/11), I was using CUDA host driver 515.xx. At that time, my path setting command in `docker_installation_guide.md` works well. In the context that CUDA host driver is old, we don't need to add the `nvcc` compiler at `/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin` to the `$PATH`. 

But this week I upgraded my CUDA host driver to latest, as also reported by some students (See [Issue 13](https://github.com/tonyyxliu/CSC4005-2023Fall/issues/13)), when the host machine was installed with latest version of CUDA drivers. (E.g., version 537.xx, which supports CUDA 12.2). In that case, the `nvcc` compiler in the `$PATH` will fail. 

**Update changes**

In the `docker_installation_guide.md`, I added back the command to add the correct compiler's PATH. (Referenced from [Issue 13](https://github.com/tonyyxliu/CSC4005-2023Fall/issues/13)).

I apologize for my last pull request removing the line. Now all of them are added back. 

image

**Tests**

In my host machine with latest driver (537.42), after running the command to add path in the docker, the `nvcc` compiler at `/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin` is called and it works. 

For older driver versions, these two lines may not be necessary. The default `nvcc` compiler may also work. I added relevant comments near these two lines.

### CODE REVIEW

**Comment by tonyyxliu** [comment]
Thank you for your PR. I also noticed that the initial system path configuration regarding CUDA-11.4 was removed from the document.

Besides, it seems that many students screw up their $PATH with these two commands. One student even showed me that his $PATH consists of over 50 paths with redundancy inside. I am afraid they call executing these two commands. I think we need to make a clarification in the document ASAP.
```bash
echo export 'LD_LIBRARY_PATH'=`echo $LD_LIBRARY_PATH`:'$LD_LIBRARY_PATH' >> ~/.bashrc
echo export 'PATH'=`echo $PATH`:'$PATH' >> ~/.bashrc
```

Again, thank you for your continuous support and kindness!

**Review by tonyyxliu — APPROVED** [review]
Thank you for such a helpful PR!

**Comment by I-am-Future** [comment]
> Thank you for your PR. I also noticed that the initial system path configuration regarding CUDA-11.4 was removed from the document.
> 
> Besides, it seems that many students screw up their $PATH with these two commands. One student even showed me that his $PATH consists of over 50 paths with redundancy inside. I am afraid they call executing these two commands. I think we need to make a clarification in the document ASAP.
> 
> ```shell
> echo export 'LD_LIBRARY_PATH'=`echo $LD_LIBRARY_PATH`:'$LD_LIBRARY_PATH' >> ~/.bashrc
> echo export 'PATH'=`echo $PATH`:'$PATH' >> ~/.bashrc
> ```
> 
> Again, thank you for your continuous support and kindness!

It's normal to have a long path, I think. As you can see in the screenshot below, It is from raw `sh`, but not `bash`, it contains so many $PATH by default. 

image

Therefore when we're using the `bash` with `ssh connect`, we need to export these `PATH`, `LD_LIBRARY_PATH` to the .bashrc. (So my last pull request did this).

Also, you may notice that the $PATH from `sh` are all directories from path like `/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/`, which contains old version of `nvcc`. The recent added command added new `nvcc` (cuda 11.4 supported) to the .bashrc as well.

**Comment by tonyyxliu** [comment]
Thank you for what you've done in this PR!
0.5 extra credits on BB for you

**Pull request merged**
